### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by vird** [unbornchikken/node-ffi#2]
node -v
v0.10.30

npm -v
2.13.4
note:same was on older npm

https://gist.github.com/vird/ef8c30991fc338f80658

In fact i want install nooocl, but it fails because ffi-io.
npm i nooocl@0.9.10 installs ok
npm i nooocl@0.9.12 fails

**Comment by unbornchikken** [comment]
Sorry, I forgot to handle NAN 2.x issue in NOOOCL. Please try the latest. It should work on any version other than io.js 3.x. For supporting that I'm waiting for ref*, and weak modules NAN 2.x support.
